### ISSUE TITLE
1. Make the white home section

### ISSUE THREAD

**Issue by AnisyaPurnama** [emelysalmeron/duck-duck-clone#2]
- [x] Develope locally on a branch called white
- [x] Assign to Anisya
- [x] Make pull request
- [ ] Merge with master

#### HTML
- [x] add link with flexboxgrid.css
- [x] add link with font-awesome.css
- [x] add link with the css.style file
- [x] create navbar
- [x] add the DuckduckGo Logo
- [x] add searchbar and button
- [x] add text under the searchbar
- [x] add extra logo (image climber.png)

#### CSS
- [x] styling the navbar
- [x] styling the logo
- [x] styling the searchbar and button
- [x] styling the text
- [x] styling the extra logo

**Comment by AnisyaPurnama** [comment]
@krakla @Ina-arpine @emelysalmeron could anyone help me with the styling css. Because it's seems like the searchbar and some image not in the right place. I already try to fix it, but not working. Oops! 😁

**Comment by krakla** [comment]
Hi @AnisyaPurnama, I try to do one template for css file. I read a lot for that to make it looks like DuckDuckGo site. I will try to share it tonight after finish it. 😉

**Comment by AnisyaPurnama** [comment]
@krakla thank you abu.. could you also review my code please.
