### ISSUE TITLE
2. Make the Green section

### ISSUE THREAD

**Issue by AnisyaPurnama** [emelysalmeron/duck-duck-clone#3]

**Comment by emelysalmeron** [comment]
- [x] Develop locally on a branch called __green__
- [x] Assign to Emely
- [x] Create a branch called __green__
- [x] Push it to  __green__
- [x] Make pull request
- [ ] Merge with master

#### HTML
- [x] Create HTML file structure called __greenbranch.html__
- [x] Add <section>
- [x] Add  <div class> 
- [x] Add image "woman with monster"

#### CSS
- [x] Style the background: #58B792
- [x] Upload image
